spring:
  application:
    name: back-end
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gallery
    username: root
    password: root123!@#

server:
  port: 9090